on:
  push:
    branches: 
      - main
      - '[0-9]+.[0-9]+.x'
      - '[0-9]+.x.x'
      - '[0-9]+.x'
      - next
      - next-major
      - alpha
      - beta
  pull_request:
    branches:
      - main
      - '[0-9]+.[0-9]+.x'
      - '[0-9]+.x.x'
      - '[0-9]+.x'
      - next
      - next-major
      - alpha
      - beta

concurrency:
  group: ${{ github.head_ref || github.ref_name }} 
  cancel-in-progress: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: corepack enable pnpm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile --prefer-offline --reporter=append-only
      - run: npm run lint

  publish:

    needs: prepare

    if: github.ref_name == 'main'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: corepack enable pnpm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile --prefer-offline --reporter=append-only
      - uses: changesets/action@v1
        with:
          commit: "chore: update versions"
          title: "chore: release"
          publish: "pnpm run ci:publish"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}